ZSH=$HOME/.oh-my-zsh

# You can change the theme with another one from https://github.com/robbyrussell/oh-my-zsh/wiki/themes
ZSH_THEME="robbyrussell"

# Useful oh-my-zsh plugins for Le Wagon bootcamps
plugins=(git gitfast common-aliases zsh-syntax-highlighting nvm fzf ssh-agent)

# nvm lazy loading (with nvm plugin)
zstyle ':omz:plugins:nvm' lazy yes
# This lists custom commands that will load nvm (nvim need it for copilot)
zstyle ':omz:plugins:nvm' lazy-cmd nvim code codium rails ruby python pip pipenv

# NO NEED OF THIS WITH FZF PLUGIN: fzf (installed via github)
# [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND="find . -not \( -path '*/.git' -prune \)"

# (macOS-only) Prevent Homebrew from reporting - https://github.com/Homebrew/brew/blob/master/docs/Analytics.md
export HOMEBREW_NO_ANALYTICS=1

# Disable warning about insecure completion-dependent directories
ZSH_DISABLE_COMPFIX=true

# Actually load Oh-My-Zsh
source "${ZSH}/oh-my-zsh.sh"
unalias rm # No interactive rm by default (brought by plugins/common-aliases)
unalias lt # we need `lt` for https://github.com/localtunnel/localtunnel

# Load rbenv if installed (to manage your Ruby versions)
export PATH="${HOME}/.rbenv/bin:${PATH}" # Needed for Linux/WSL
type -a rbenv > /dev/null && eval "$(rbenv init - zsh)"

# Load pyenv (to manage your Python versions)
# export PYENV_VIRTUALENV_DISABLE_PROMPT=1
# type -a pyenv > /dev/null && eval "$(pyenv init -)" && eval "$(pyenv virtualenv-init -)" && RPROMPT+='[🐍 $(pyenv version-name)]'

# Rails and Ruby uses the local `bin` folder to store binstubs.
# So instead of running `bin/rails` like the doc says, just run `rails`
# Same for `./node_modules/.bin` and nodejs
export PATH="./bin:./node_modules/.bin:${PATH}:/usr/local/sbin"

# Store your own aliases in the ~/.aliases file and load the here.
[[ -f "$HOME/.aliases" ]] && source "$HOME/.aliases"

# Encoding stuff for the terminal
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

export BUNDLER_EDITOR=nvim
export EDITOR=nvim

# Set ipdb as the default Python debugger
export PYTHONBREAKPOINT=ipdb.set_trace

# OCGG

export PATH=$PATH:~/code/ftrack
export PATH=$PATH:~/.local/bin
export GOBIN=$HOME/go/bin/
export PATH=$PATH:$GOBIN
# avoid __pycache__ folder generation in python project folders
export PYTHONPYCACHEPREFIX=/tmp/python/__pycache__

export LXVST_PATH=/usr/lib64/vst:~/.vst
export VST3_PATH=~/.vst3
export LADSPA_PATH=/usr/lib64/ladspa
export LV2_PATH=/usr/lib64/lv2:~/.lv2

# For Ardour
export XDG_CONFIG_HOME=~/.config
